desc: "Xen-Troops development setup for Xilinx Zynq UltraScale+ MPSoC hardware"
min_ver: "0.8"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOMU_BUILD_DIR: "build-domu"
  DOMZ_DIR: "zephyr"
  XT_XEN_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-xen.dtb"
  XT_DOMU_TAG: "domu"
  XT_DOMZ_TAG: ""
  # For this product we use one config for all machines for Zephyr
  XT_DOMZ_CONFIG_NAME: "domz-generic.cfg"
  REVISION_OF_RELEASE: "rel-v2022.2"
common_data:
  # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../../../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../../../common_data/downloads"]

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      # List of repositories is taken from
      # https://github.com/Xilinx/yocto-manifests/blob/rel-v2022.2/default.xml
      # commit 39cab8602eb148669136025cdd33b851c3872200
      - type: git
        url: "https://github.com/Xilinx/meta-browser"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-clang"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-jupyter"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-mingw"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-openamp"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-openembedded"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-petalinux"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-python2"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-qt5"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-security"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-som"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-virtualization"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-xilinx"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-xilinx-tools"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/poky"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/yocto-manifests"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/yocto-scripts"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-ros"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-xilinx-tsn"
        rev: "rel-v2022.2"
      - type: git
        url: "https://github.com/Xilinx/meta-vitis"
        rev: "rel-v2022.2"
      - type: git
        url: "git@github.com:rshym/meta-xt-prod-devel-zynq.git"
        rev: "main"
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "zcu102-zynqmp"]
        - [DISTRO, "petalinux"]
        # Add alternative mirrors for some components
        #- [INHERIT:append, " plnx-mirrors"]
        #- [DISTRO_FEATURES:append, " xen"]
        #- [DISTRO_FEATURES:append, " virtualization"]
        #- [IMAGE_FEATURES:append, " ssh-server-dropbear"]
        #- [IMAGE_INSTALL:append, " busybox xen-tools qemu zlib-dev screen util-linux-prlimit"]
        #- [ASSUME_PROVIDED:append, "iasl-native"]
        #- [PACKAGECONFIG:pn-qemu:append, " virtfs xen fdt"]
        #- [PACKAGECONFIG:remove:pn-xen, " sdl"]
        - [XT_DOMZ_CONFIG_NAME, "%{XT_DOMZ_CONFIG_NAME}"]
        - [XT_DOM_NAME, "dom0"]
        - [XT_GUEST_INSTALL, "%{XT_DOMU_TAG} %{XT_DOMZ_TAG}"]

      layers:
        # list of layers is from meta-petalinux/conf/bblayers.conf.sample
        # obtained by revision from `sources` above
        - "../meta-openembedded/meta-perl"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-gnome"
        - "../meta-openembedded/meta-multimedia"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-webserver"
        - "../meta-openembedded/meta-xfce"
        - "../meta-openembedded/meta-initramfs"
        - "../meta-openembedded/meta-oe"
        - "../meta-clang"
        - "../meta-browser/meta-chromium"
        - "../meta-qt5"
        - "../meta-xilinx/meta-microblaze"
        - "../meta-xilinx/meta-xilinx-core"
        - "../meta-xilinx/meta-xilinx-bsp"
        - "../meta-xilinx/meta-xilinx-pynq"
        - "../meta-xilinx/meta-xilinx-contrib"
        - "../meta-xilinx/meta-xilinx-standalone"
        - "../meta-xilinx/meta-xilinx-vendor"
        - "../meta-xilinx-tools"
        - "../meta-petalinux"
        - "../meta-virtualization"
        - "../meta-openamp"
        - "../meta-jupyter"
        - "../meta-vitis"
        - "../meta-python2"
        - "../meta-som"
        - "../meta-security"
        - "../meta-security/meta-tpm"
        - "../meta-xilinx-tsn"
        - "../meta-ros/meta-ros-common"
        - "../meta-ros/meta-ros2"
        - "../meta-ros/meta-ros2-humble"
        - "../meta-xt-prod-devel-zynq/meta-xt-dom0"
        - "../meta-xt-prod-devel-zynq/meta-xt-control-domain"

      build_target: petalinux-image-minimal
      #external_src:
      #  see ENABLE_ZEPHYR below
      #additional_deps:
      #  see ENABLE_ZEPHYR below
      target_images:
        # all paths are relative to %{DOM0_BUILD_DIR}
        - "tmp/deploy/images/%{MACHINE}/atf-uboot.ub"
        - "tmp/deploy/images/%{MACHINE}/boot_xen.scr"
        - "tmp/deploy/images/%{MACHINE}/Image"
        - "tmp/deploy/images/%{MACHINE}/system.dtb"
        - "tmp/deploy/images/%{MACHINE}/u-boot.bin"
        - "tmp/deploy/images/%{MACHINE}/uEnv.txt"
        - "tmp/deploy/images/%{MACHINE}/zynqmp-zcu102-rev1.0.dtb"
        - "tmp/deploy/images/%{MACHINE}/xen.ub"
        # rootfs
        - "tmp/deploy/images/%{MACHINE}/xen-image-minimal-%{MACHINE}.ext4"

  domu:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - type: git
        url: "https://github.com/Xilinx/poky"
        rev: "rel-v2022.2"
      - type: git
        url: "git@github.com:rshym/meta-xt-prod-devel-zynq.git"
        rev: "main"
    builder:
      type: yocto
      work_dir: "%{DOMU_BUILD_DIR}"
      conf:
        - [XT_DOM_NAME, "domu"]
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../meta-xt-prod-devel-zynq/meta-xt-domu"
      build_target: core-image-thin-initramfs
      target_images:
        - "tmp/deploy/images/%{MACHINE}/Image"
        #- "tmp/deploy/images/%{MACHINE}/core-image-weston-%{MACHINE}.ext4"

  zephyr:
    build-dir: "%{DOMZ_DIR}"
    sources:
      - type: west
        #url: https://github.com/sstabellini/zephyr
        #rev: elc22
        url: git@github.com:rshym/zephyr.git
        #rev: rebased_elc22
    builder:
      type: zephyr
      board: xenvm
      target: samples/hello_world
      target_images:
        - "zephyr/build/zephyr/zephyr.bin"

images:
  full:
    type: gpt
    image_size: 512 MiB
    desc: "Full SD-card/eMMC image"
    partitions:
      boot:
        gpt_type: EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 # Windows Basic data partition
        type: vfat
        files:
          "atf-uboot.ub": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/atf-uboot.ub"
          "boot.scr": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/boot_xen.scr"
          "Image": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
          "system.dtb": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/system.dtb"
          "u-boot.bin": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/u-boot.bin"
          "uEnv.txt": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/uEnv.txt"
          "zynqmp-zcu102-rev1.0.dtb": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/zynqmp-zcu102-rev1.0.dtb"
          "xen.ub": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xen.ub"
      dom0_rootfs:
        gpt_type: c7585248-d0b9-4bfb-9a30-2cfdfe16dc4e # Linux
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/xen-image-minimal-%{MACHINE}.ext4"

parameters:
  # Machines
  MACHINE:
    desc: "Zynq UltraScale+ MPSoC based device"
    zcu102-zynqmp:
      default: true
      overrides:
        variables:
          MACHINE: "zcu102-zynqmp"
          SOC_FAMILY: "XCZU9EG"
          XT_XEN_DTB_NAME: "-%{MACHINE}-xen.dtb"

  ENABLE_ZEPHYR:
    desc: "Build Zephyr as guest domain"
    "no":
      default: true
      # nothing to add
      overrides:
        variables:
          XT_DOMZ_TAG: ""
    "yes":
      overrides:
        variables:
          XT_DOMZ_TAG: "domz"
        components:
          dom0:
            builder:
              additional_deps:
                # paths relative to dom0 build-dir
                - "../%{DOMZ_DIR}/zephyr/build/zephyr/zephyr.bin"
              external_src:
                # path relative to folder containing build.ninja
                domz: "%{DOMZ_DIR}/zephyr/build/zephyr"


  # If we run under QEMU, we need to add additional binaries to full image
  ENABLE_QEMU:
    desc: "Enable use of inage under QEMU"
    "no":
      default: true
    "yes":
      overrides:
        components:
          dom0:
            builder:
              target_images:
                # qemu related targets
                - "tmp/deploy/images/%{MACHINE}/qemu-hw-devicetrees/multiarch/zcu102-arm.dtb"
                - "tmp/deploy/images/%{MACHINE}/qemu-hw-devicetrees/multiarch/zynqmp-pmu.dtb"
                - "tmp/deploy/images/%{MACHINE}/arm-trusted-firmware.elf"
                - "tmp/deploy/images/%{MACHINE}/u-boot.elf"
                - "tmp/deploy/images/%{MACHINE}/pmu-firmware-zcu102-zynqmp.elf"
        images:
          full:
            partitions:
              boot:
                files:
                  "zcu102-arm.dtb": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/qemu-hw-devicetrees/multiarch/zcu102-arm.dtb"
                  "zynqmp-pmu.dtb": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/qemu-hw-devicetrees/multiarch/zynqmp-pmu.dtb"
                  "arm-trusted-firmware.elf": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/arm-trusted-firmware.elf"
                  "u-boot.elf": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/u-boot.elf"
                  #"pmu-rom.elf": "%{XT_PMU_ROM_DIR}/pmu-rom.elf"
                  "pmu-firmware-zcu102-zynqmp.elf": "%{YOCTOS_WORK_DIR}/%{DOM0_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/pmu-firmware-zcu102-zynqmp.elf"

